name: Validate JSON

on:
  push:
    paths:
      - 'verified-tokens.json'
  pull_request:
    paths:
      - 'verified-tokens.json'

jobs:
  json-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install JSONLint
        run: npm install -g jsonlint

      - name: Lint verified-tokens.json
        run: jsonlint verified-tokens.json
